/**
 * Source dataset for the 1Fi Marketplace.
 *
 * This file is the *seed source* only — it is loaded into the
 * SQLite database by `npm run seed` (or automatically on first
 * server boot). The React UI never reads this file; it fetches
 * everything through the REST API.
 *
 * EMI monthly amounts are NOT hardcoded here — they are computed
 * by the seed script using the standard EMI formula.
 */

export const products = [
  {
    slug: 'apple-iphone-17-pro',
    name: 'Apple iPhone 17 Pro',
    brand: 'Apple',
    category: 'Smartphones',
    description:
      'The iPhone 17 Pro is built for people who want the absolute best — a lighter titanium design, the fastest A19 Pro chip Apple has ever made, and a pro-grade camera system that makes every shot look studio-quality. Pay over time with 1Fi\u2019s mutual-fund-backed EMI plans and keep your savings invested while you upgrade.',
    highlights: [
      'A19 Pro chip with 6-core GPU — desktop-class performance',
      '48MP Pro camera system with 5x tetraprism telephoto',
      '6.3-inch Super Retina XDR display, ProMotion 120Hz',
      'Titanium design with second-gen Ceramic Shield',
      'All-day battery with USB-C fast charging',
    ],
    specs: [
      { label: 'Display', value: '6.3-inch Super Retina XDR, 120Hz ProMotion' },
      { label: 'Processor', value: 'A19 Pro (3nm)' },
      { label: 'Camera', value: '48MP main + 48MP ultrawide + 12MP 5x telephoto' },
      { label: 'Battery', value: 'Up to 27 hours video playback' },
      { label: 'Charging', value: 'USB-C, MagSafe wireless' },
      { label: 'Weight', value: '199 g' },
    ],
    variants: [
      {
        name: 'Silver \u00b7 256 GB',
        color: 'Silver',
        finish: 'Titanium',
        storage: '256 GB',
        swatch: '#E3E4E5',
        mrp: 139900,
        price: 124999,
        image: '/images/iphone-17-pro-silver.png',
      },
      {
        name: 'Lavender \u00b7 256 GB',
        color: 'Lavender',
        finish: 'Titanium',
        storage: '256 GB',
        swatch: '#B9AED6',
        mrp: 139900,
        price: 124999,
        image: '/images/iphone-17-pro-lavender.png',
      },
      {
        name: 'Black Titanium \u00b7 512 GB',
        color: 'Black Titanium',
        finish: 'Titanium',
        storage: '512 GB',
        swatch: '#2E2E30',
        mrp: 159900,
        price: 144999,
        image: '/images/iphone-17-pro-black-titanium.png',
      },
      {
        name: 'Cosmic Orange \u00b7 1 TB',
        color: 'Cosmic Orange',
        finish: 'Titanium',
        storage: '1 TB',
        swatch: '#E85D26',
        mrp: 189900,
        price: 172999,
        image: '/images/iphone-17-pro-cosmic-orange.png',
      },
    ],
    plans: [
      { tenure: 3, rate: 0, fund: '1Fi Liquid Fund', cashback: null, featured: false },
      {
        tenure: 6,
        rate: 0,
        fund: '1Fi Nifty 50 Index Fund',
        cashback: { type: 'flat', value: 1500 },
        featured: true,
      },
      { tenure: 9, rate: 10.5, fund: '1Fi Flexi Cap Fund', cashback: null, featured: false },
      {
        tenure: 12,
        rate: 10.5,
        fund: '1Fi Flexi Cap Fund',
        cashback: { type: 'flat', value: 2500 },
        featured: false,
      },
    ],
  },
  {
    slug: 'samsung-galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Smartphones',
    description:
      'Meet the Galaxy S24 Ultra — a titanium-framed flagship with Galaxy AI, the built-in S Pen, and a 200MP camera that captures detail you didn\u2019t even know was there. Live-translate calls, circle-to-search anything on screen, and edit photos like a pro — all powered by Galaxy AI.',
    highlights: [
      'Galaxy AI — live translate, circle-to-search, photo assist',
      '200MP quad camera with 100x Space Zoom',
      '6.8-inch QHD+ Dynamic AMOLED 2X, 120Hz',
      'S Pen included — note, sketch and control from afar',
      'Titanium frame, IP68 water resistance',
    ],
    specs: [
      { label: 'Display', value: '6.8-inch QHD+ Dynamic AMOLED 2X, 120Hz' },
      { label: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
      { label: 'Camera', value: '200MP + 50MP + 12MP + 10MP, 100x Space Zoom' },
      { label: 'Battery', value: '5000 mAh, 45W fast charging' },
      { label: 'S Pen', value: 'Included in the box' },
      { label: 'Weight', value: '232 g' },
    ],
    variants: [
      {
        name: 'Titanium Gray \u00b7 256 GB',
        color: 'Titanium Gray',
        finish: 'Titanium',
        storage: '256 GB',
        swatch: '#8F9296',
        mrp: 129999,
        price: 112999,
        image: '/images/pixel-9-pro-rose-quartz.png',
      },
      {
        name: 'Titanium Violet \u00b7 512 GB',
        color: 'Titanium Violet',
        finish: 'Titanium',
        storage: '512 GB',
        swatch: '#B9A7C7',
        mrp: 139999,
        price: 121999,
        image: '/images/galaxy-s24-ultra-titanium-violet.png',
      },
      {
        name: 'Titanium Black \u00b7 1 TB',
        color: 'Titanium Black',
        finish: 'Titanium',
        storage: '1 TB',
        swatch: '#1F2123',
        mrp: 159999,
        price: 139999,
        image: '/images/pixel-9-pro-hazel.png',
      },
    ],
    plans: [
      { tenure: 3, rate: 0, fund: '1Fi Liquid Fund', cashback: null, featured: false },
      {
        tenure: 6,
        rate: 0,
        fund: '1Fi Nifty 50 Index Fund',
        cashback: { type: 'flat', value: 2000 },
        featured: true,
      },
      { tenure: 12, rate: 10.5, fund: '1Fi Flexi Cap Fund', cashback: null, featured: false },
      {
        tenure: 18,
        rate: 11.5,
        fund: '1Fi Mid Cap Fund',
        cashback: { type: 'flat', value: 3000 },
        featured: false,
      },
    ],
  },
  {
    slug: 'google-pixel-9-pro',
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    category: 'Smartphones',
    description:
      'The Pixel 9 Pro is Google\u2019s most powerful phone yet, powered by Tensor G4. Gemini lives right on the device — helping with screenshots, calls and everything in between — while the 50MP camera nails every shot with Google\u2019s legendary computational photography.',
    highlights: [
      'Gemini built in — an AI assistant you can actually talk to',
      '50MP main + 48MP ultrawide + 48MP 5x telephoto camera',
      '6.3-inch Super Actua OLED, 120Hz',
      '7 years of OS and security updates',
      'Premium matte glass with polished metal frame',
    ],
    specs: [
      { label: 'Display', value: '6.3-inch Super Actua OLED, 120Hz' },
      { label: 'Processor', value: 'Google Tensor G4' },
      { label: 'Camera', value: '50MP + 48MP + 48MP triple camera' },
      { label: 'Battery', value: '4700 mAh, 30W fast charging' },
      { label: 'Updates', value: '7 years of OS + security updates' },
      { label: 'Weight', value: '199 g' },
    ],
    variants: [
      {
        name: 'Obsidian \u00b7 128 GB',
        color: 'Obsidian',
        finish: 'Matte glass',
        storage: '128 GB',
        swatch: '#2B2D31',
        mrp: 109999,
        price: 94999,
        image: '/images/pixel-9-pro-obsidian.png',
      },
      {
        name: 'Flowy Emerald \u00b7 256 GB',
        color: 'Flowy Emerald',
        finish: 'Matte glass',
        storage: '256 GB',
        swatch: '#BDD4C0',
        mrp: 119999,
        price: 103999,
        image: '/images/oneplus-12-flowy-emerald.png',
      },
      {
        name: 'Silky Black \u00b7 512 GB',
        color: 'Silky Black',
        finish: 'Matte',
        storage: '512 GB',
        swatch: '#3A3A3A',
        mrp: 139999,
        price: 124999,
        image: '/images/oneplus-12-silky-black.png',
      },
    ],
    plans: [
      { tenure: 3, rate: 0, fund: '1Fi Liquid Fund', cashback: null, featured: false },
      {
        tenure: 6,
        rate: 0,
        fund: '1Fi Nifty 50 Index Fund',
        cashback: { type: 'flat', value: 1500 },
        featured: true,
      },
      { tenure: 9, rate: 10.5, fund: '1Fi Flexi Cap Fund', cashback: null, featured: false },
      {
        tenure: 12,
        rate: 10.5,
        fund: '1Fi Flexi Cap Fund',
        cashback: { type: 'flat', value: 2500 },
        featured: false,
      },
    ],
  },
  {
    slug: 'oneplus-12',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    category: 'Smartphones',
    description:
      'The OnePlus 12 brings true flagship muscle to the table — Snapdragon 8 Gen 3, a gorgeous 2K ProXDR display, and a Hasselblad-tuned 50MP triple camera with a 64MP periscope telephoto that punches way above its price. With 100W SUPERVOOC charging, you\u2019re back to full power in about 26 minutes.',
    highlights: [
      'Snapdragon 8 Gen 3 — the fastest OnePlus yet',
      'Hasselblad-tuned 50MP main + 64MP 3x periscope telephoto',
      '6.82-inch 2K ProXDR LTPO display, 120Hz',
      '100W SUPERVOOC — full charge in 26 minutes',
      '5400 mAh battery with advanced cooling',
    ],
    specs: [
      { label: 'Display', value: '6.82-inch 2K LTPO AMOLED, 120Hz' },
      { label: 'Processor', value: 'Snapdragon 8 Gen 3' },
      { label: 'Camera', value: '50MP + 64MP periscope (3x) + 48MP ultrawide, Hasselblad' },
      { label: 'Battery', value: '5400 mAh, 100W SUPERVOOC' },
      { label: 'Charging', value: '100W wired, 50W wireless' },
      { label: 'Weight', value: '220 g' },
    ],
    variants: [
      {
        name: 'Cool Blue \u00b7 256 GB',
        color: 'Cool Blue',
        finish: 'Glossy',
        storage: '256 GB',
        swatch: '#A8D1EC',
        mrp: 64999,
        price: 57999,
        image: '/images/oneplus-12-cool-blue.png',
      },
      {
        name: 'Silky Black \u00b7 512 GB',
        color: 'Silky Black',
        finish: 'Matte',
        storage: '512 GB',
        swatch: '#2A2A2C',
        mrp: 69999,
        price: 61999,
        image: '/images/oneplus-12-silky-black-512.png',
      },
    ],
    plans: [
      { tenure: 3, rate: 0, fund: '1Fi Liquid Fund', cashback: null, featured: false },
      {
        tenure: 6,
        rate: 0,
        fund: '1Fi Nifty 50 Index Fund',
        cashback: { type: 'flat', value: 1000 },
        featured: true,
      },
      { tenure: 9, rate: 10.5, fund: '1Fi Flexi Cap Fund', cashback: null, featured: false },
      {
        tenure: 12,
        rate: 10.5,
        fund: '1Fi Flexi Cap Fund',
        cashback: { type: 'flat', value: 1500 },
        featured: false,
      },
    ],
  },
];